### ISSUE TITLE
JWT not verifying properly

### ISSUE THREAD

**Issue by joshua-richardson-88** [passageidentity/passage-node#41]
Steps to verify - 

1. clone this [repo](https://github.com/joshua-richardson-88/passage-next-demo). 
2. Add env file with variables for passage app
3. Login 

I had to dig pretty deep to figure out what was going on. From my testing what is happening is the login is occurring correctly on the home page and storing the JWT in the cookies. When redirecting to the /dashboard page, in getServerSideProps I'm validating the token and the token is failing. What is happening is the redirect is occuring so quickly that the "nbf" property in the JSON is after the validation function is rendering.

The value was "nbf": 1662616577, and the time that the token was evaluated was 1662616576580, or just over 400ms before the token is available to be used.

Maybe the token should have a nbf value of a few seconds before the request to prevent this kind of overlap?

**Comment by calhorn95** [comment]
Hello @joshua-richardson-88.  Thank you for reporting this issue.  After cloning your repo, I was able to reproduce the bug you were seeing regarding the JWT "nbf".  We have just released an update to our JWT creation logic to set the "nbf" to 5 seconds before the "iat".  This conforms to the [JWT spec](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.5) and will provide us with some leeway to deal with clock skew.

Please try it out and make sure that you are no longer having any issues authenticating your JWTs.

I will be closing this issue, but if the issue persists for you please comment and reopen this same issue report.

**Comment by joshua-richardson-88** [comment]
Hi there, I have tried this out several times since this ticket has closed - and I'm still receiving the NotBeforeError on validating the jwt. It seems like 5 seconds was added to the nbf field (5 seconds further into the future) than before. A sample I have from time 1662870892451 is "nbf": 1662870897

**Comment by yorsant** [comment]
I'm following the [instructions](https://docs.passage.id/helpful-guides/supabase-integration-guide) for a next js app but using the new app router instead of the pages router.
Once I call `passage.authenticateRequest(req)` I get **Error: Could not find valid cookie for authentication.**

These are the cookies in my browser after successful authentication. 
![Screenshot 2023-06-10 at 11 39 09 PM](https://github.com/passageidentity/supabase-passage-example/assets/12414043/5064582c-b32a-4761-ac59-1d6c6b27f3f3)


#references https://github.com/passageidentity/supabase-passage-example/issues/5#issue-1751221374
